import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import notaxPaySidebar from './docs/notax-pay/sidebar';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introdução',
    },
    {
      // Autogerado a partir da pasta docs/guias — adicione um .mdx lá e ele
      // aparece aqui automaticamente. A ordem vem do `sidebar_position` de cada arquivo.
      type: 'category',
      label: 'Guias',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'guias' }],
    },
    {
      type: 'category',
      label: 'Notax Pay',
      collapsible: false,
      items: notaxPaySidebar,
    },
  ],
};

export default sidebars;
